"""Differentiable radio-interferometric sky–instrument modelling."""

from jax import config as _jax_config

_jax_config.update("jax_enable_x64", True)

from sl1mjax.beam import (  # noqa: E402
    VLABeamCatalog,
    VLAPrimaryBeam,
    gaussian_primary_beam,
    primary_beam_from_name,
)
from sl1mjax.calibration import (  # noqa: E402
    CalibrationSolution,
    apply_calibration,
    identity_solution,
)
from sl1mjax.calibration_diagnostics import diagnose_calibration  # noqa: E402
from sl1mjax.calibration_inference import (  # noqa: E402
    CalibrationFitResult,
    CalibrationSolveConfig,
    solve_staged_calibration,
)
from sl1mjax.calibration_terms import (  # noqa: E402
    CalibrationChain,
    CalibrationCoordinates,
    GainCurveTerm,
    OpacityTerm,
    RequantizerTerm,
)
from sl1mjax.coordinates import lmn_to_radec, radec_to_lmn  # noqa: E402
from sl1mjax.data import (  # noqa: E402
    VisibilityBlock,
    VisibilityDataset,
    read_dataset,
    write_dataset,
)
from sl1mjax.diagnostics import (  # noqa: E402
    ResidualEvaluation,
    dirty_image_and_psf,
    evaluate_residuals,
)
from sl1mjax.direct_operator import (  # noqa: E402
    DirectDFTConfig,
    direct_scalar_adjoint,
    direct_scalar_visibility,
    predict_stokes_i_explicit,
)
from sl1mjax.hierarchical_imaging import (  # noqa: E402
    AdaptiveRefinementConfig,
    AdaptiveRefinementRound,
    HierarchicalImagingResult,
    reconstruct_hierarchical,
)
from sl1mjax.imaging import ImagingConfig, ImagingResult, reconstruct  # noqa: E402
from sl1mjax.inference import (  # noqa: E402
    InferenceConfig,
    InferenceResult,
    QuadtreeInferenceResult,
    infer_quadtree,
    infer_regular_grid,
)
from sl1mjax.polarization import Correlation, ReceptorBasis  # noqa: E402
from sl1mjax.quadtree import (  # noqa: E402
    QuadtreeGrid,
    QuadtreeLeaf,
    QuadtreeSky,
    QuadtreeTopology,
    leaves_exceeding_error_bound,
    predict_quadtree_stokes_i,
    predict_quadtree_stokes_i_explicit,
    quadtree_sky_from_regular_grid,
    wide_field_error_bounds,
)
from sl1mjax.refinement import (  # noqa: E402
    BulkMergeSelection,
    BulkSplitSelection,
    ExhaustiveMergeResult,
    ExhaustiveSplitResult,
    HaarOracleComparison,
    LocalMergeEvaluation,
    LocalMergeResult,
    LocalSplitEvaluation,
    LocalSplitResult,
    LookaheadOracleComparison,
    LookaheadRankingEntry,
    MergeHysteresisState,
    MergeLookaheadOracleComparison,
    MergeRankingEntry,
    QuadtreeObjectiveMetrics,
    RefinementAttempt,
    RefinementBatchResult,
    ResidualHaarScore,
    SingleMergeEvaluation,
    SingleSplitEvaluation,
    SplitBaselineScore,
    SplitRankingEntry,
    advance_merge_hysteresis,
    baseline_split_scores,
    batched_residual_haar_scores,
    compare_haar_to_oracle,
    compare_lookahead_to_oracle,
    compare_merge_lookahead_to_oracle,
    exhaustive_single_merge_oracle,
    exhaustive_single_split_oracle,
    local_four_child_lookahead,
    local_four_sibling_merge_lookahead,
    merge_quadtree_batch,
    mergeable_parents,
    quadtree_objective_metrics,
    refine_quadtree_batch,
    render_quadtree_surface_brightness,
    residual_haar_scores,
    select_bulk_merges,
    select_bulk_splits,
    solve_quadtree_flux_active_set,
)
from sl1mjax.rime import (  # noqa: E402
    predict_stokes_i,
    square_wide_field_error_bound,
)
from sl1mjax.sky import (  # noqa: E402
    COMPOUND_N4_BASIS,
    CompoundPixelBasis,
    DeltaPixelBasis,
    GaussianApproximation,
    GaussianPixelBasis,
    RegularGrid,
    SquarePixelBasis,
    pixel_basis_from_name,
)

__all__ = [
    "Correlation",
    "BulkMergeSelection",
    "BulkSplitSelection",
    "CalibrationFitResult",
    "AdaptiveRefinementConfig",
    "AdaptiveRefinementRound",
    "CalibrationChain",
    "CalibrationCoordinates",
    "CalibrationSolution",
    "CalibrationSolveConfig",
    "COMPOUND_N4_BASIS",
    "CompoundPixelBasis",
    "DeltaPixelBasis",
    "DirectDFTConfig",
    "ExhaustiveMergeResult",
    "ExhaustiveSplitResult",
    "HaarOracleComparison",
    "HierarchicalImagingResult",
    "GaussianApproximation",
    "GaussianPixelBasis",
    "GainCurveTerm",
    "ImagingConfig",
    "ImagingResult",
    "InferenceConfig",
    "InferenceResult",
    "LocalMergeEvaluation",
    "LocalMergeResult",
    "LocalSplitEvaluation",
    "LocalSplitResult",
    "LookaheadOracleComparison",
    "LookaheadRankingEntry",
    "MergeHysteresisState",
    "MergeLookaheadOracleComparison",
    "MergeRankingEntry",
    "QuadtreeGrid",
    "QuadtreeInferenceResult",
    "QuadtreeLeaf",
    "QuadtreeSky",
    "QuadtreeTopology",
    "QuadtreeObjectiveMetrics",
    "RefinementAttempt",
    "RefinementBatchResult",
    "ReceptorBasis",
    "RequantizerTerm",
    "RegularGrid",
    "VLABeamCatalog",
    "VLAPrimaryBeam",
    "ResidualEvaluation",
    "ResidualHaarScore",
    "OpacityTerm",
    "SquarePixelBasis",
    "SingleMergeEvaluation",
    "SingleSplitEvaluation",
    "SplitBaselineScore",
    "SplitRankingEntry",
    "VisibilityBlock",
    "VisibilityDataset",
    "advance_merge_hysteresis",
    "apply_calibration",
    "baseline_split_scores",
    "batched_residual_haar_scores",
    "compare_haar_to_oracle",
    "compare_lookahead_to_oracle",
    "compare_merge_lookahead_to_oracle",
    "diagnose_calibration",
    "dirty_image_and_psf",
    "direct_scalar_adjoint",
    "direct_scalar_visibility",
    "evaluate_residuals",
    "exhaustive_single_merge_oracle",
    "exhaustive_single_split_oracle",
    "gaussian_primary_beam",
    "infer_regular_grid",
    "infer_quadtree",
    "identity_solution",
    "leaves_exceeding_error_bound",
    "lmn_to_radec",
    "local_four_child_lookahead",
    "local_four_sibling_merge_lookahead",
    "mergeable_parents",
    "merge_quadtree_batch",
    "pixel_basis_from_name",
    "primary_beam_from_name",
    "predict_quadtree_stokes_i",
    "predict_quadtree_stokes_i_explicit",
    "predict_stokes_i",
    "predict_stokes_i_explicit",
    "quadtree_sky_from_regular_grid",
    "quadtree_objective_metrics",
    "refine_quadtree_batch",
    "radec_to_lmn",
    "read_dataset",
    "reconstruct",
    "reconstruct_hierarchical",
    "render_quadtree_surface_brightness",
    "residual_haar_scores",
    "select_bulk_merges",
    "select_bulk_splits",
    "solve_quadtree_flux_active_set",
    "solve_staged_calibration",
    "square_wide_field_error_bound",
    "wide_field_error_bounds",
    "write_dataset",
]

__version__ = "0.1.0"
